% ----------------------------------------------------------------------- %
% 3D Image Formation and AutoFocus ReadMe 
%
% List of program and file functionality by folder
%
% 1: Current Code 
% 
%   Folder with most recent code iterations
%
%       cutImgCube.m            - Takes an image cube (either 3D or 4D) and
%                                 returns a subsection of that cube. Used
%                                 to speed image processing time when only
%                                 sections of the image are needed.
%
%       FormAndProcessImage.m   - The parent function for radar pulse 
%                                 generation, image formation, and
%                                 autofocus. 
%
%       FormatPulseData.m       - SAR_3D processes radar information that
%                                 is formatted as if it came from the
%                                 PulsOn radar unit itself. This function
%                                 takes artificial radar data generated by
%                                 MATLAB and puts it into a form usable by
%                                 SAR_3D.
%
%       FormPulses.m            - Generations radar pulse returns from a
%                                 given set of synthetic targets. The
%                                 pulses simulate the behavior of the 
%                                 PulsOn P410, the radar unit on our drone.
%
%       minEntropyAutoFocus.m   - The minimum entropy autofocus routine.
%                                 Takes a 4D pulse image set and performs
%                                 phase corrections to focus the image/
%
%       SAR_3D.m                - Performs the backprojection necessary to
%                                 form a 3D image from a given set of radar
%                                 returns from a 2D aperture.
%
%       ViewCube.m              - Visualization tool for 3D images. Takes a
%                                 3D or 4D data set and visualizes it using
%                                 an isosurface. 
%
% 2: Data_9Points
%
%   Folder containing actual, blurred, and focused images of 9 synthetic
%   point reflectors.
%
%       Data Sets               - Except for the first two, all are 4D
%                                 pulse sets for use with autofocus. They
%                                 consist of the actual image, the blurred
%                                 image, and four iterations of autofocused
%                                 data. 
%
%       Functions               - minEntropyAutoFocus.m and ViewCube.m are
%                                 repeats from the Current Code folder.
%                                 They were placed here for convenience
%                                 when processing and viewing data.
%
% 3: Data_Diamond
%
%   Similar to the Data_9Points folder, expect with a 7-point diamond data
%   set. 
%
% 4: Large Aperture Images
%
%   Images formed with (somewhat) large apertures. Designed to see how well
%   larger apertures can integrate out GPS noise. The answer is very well.
%   There are also some apertures created with extreme noise to observe the
%   extend of autofocus...except that they crashed MATLAB since the
%   computer ran out of RAM. To be investigated later. 
%
% 5: Reference Code
%
%   Previous iterations and original pieces of autofocus data. 
%
% ----------------------------------------------------------------------- %


























